function [fitresult, gof] = createFit(fcin, Fanofactor)
global coeff;
%CREATEFIT(FCIN,FANOFACTOR)
%  Create a fit.
%
%  Data for 'R_gamma_ratio' fit:
%      X Input : fcin
%      Y Output: Fanofactor
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Feb-2017 11:53:45


%% Fit: 'R_gamma_ratio'.
[xData, yData] = prepareCurveData( fcin, Fanofactor );

% Set up fittype and options.
ft = fittype( '1+x*(a/b)*((1-x)/((.0045/b)+x))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.11816050014251 0.626926994070845];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
%figure( 'Name', 'R_gamma_ratio' );
%h = plot( fitresult, xData, yData );
%set(gca,'xscale','log');
%legend( h, 'Fanofactor vs. fcin', 'R_gamma_ratio', 'Location', 'NorthEast' );

coeff =  coeffvalues(fitresult);
coeff(1);

% Label axes
%xlabel fcin
%ylabel Fanofactor
%grid on


